pd = input.int(22, title='LookBack Period Standard Deviation High')
bbl = input.int(20, title='Bolinger Band Length')
mult = input.float(2.0, minval=1, maxval=5, title='Bollinger Band Standard Devaition Up')
lb = input.int(50, title='Look Back Period Percentile High')
ph = input.float(.85, title='Highest Percentile - 0.90=90%, 0.95=95%, 0.99=99%')
pl = input.float(1.01, title='Lowest Percentile - 1.10=90%, 1.05=95%, 1.01=99%')
hp = input.bool(true, title='Show High Range - Based on Percentile and LookBack Period?')
sd = input.bool(true, title='Show Standard Deviation Line?')

wvf = (ta.highest(close, pd) - low) / ta.highest(close, pd) * 100

sDev = mult * ta.stdev(wvf, bbl)
midLine = ta.sma(wvf, bbl)
lowerBand = midLine - sDev
upperBand = midLine + sDev

rangeHigh = ta.highest(wvf, lb) * ph
rangeLow = ta.lowest(wvf, lb) * pl

col = wvf >= upperBand or wvf >= rangeHigh ? color.lime : color.gray

RangeHigh = hp and rangeHigh ? rangeHigh : na
RangeLow = hp and rangeLow ? rangeLow : na
UpperBand = sd and upperBand ? upperBand : na

plot(RangeHigh, title='Range High Percentile', style=plot.style_line, linewidth=4, color=color.new(color.orange, 0))
plot(RangeLow, title='Range Low Percentile', style=plot.style_line, linewidth=4, color=color.new(color.orange, 0))
plot(UpperBand, title='Upper Band', style=plot.style_line, linewidth=3, color=color.new(color.aqua, 0))
plot(wvf, title='Williams Vix Fix', style=plot.style_histogram, linewidth=4, color=col)
